### ISSUE TITLE
Installing sphero.js on windows with Visualstudio Express 2015.

### ISSUE THREAD

**Issue by polymouse** [orbotix/sphero.js#29]
## Cannot install the sphero.js. Generates various build errors.

Installation log:
    E:\dev\projects\sphero>npm install sphero
    \
    > serialport@1.7.1 install E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport
    > node-pre-gyp install --fallback-to-build
    
    
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )
    
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport\v1.7.1\Release\node-v46-win32-x64\serialport.node --module_name=serialport --module_path=E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport\v1.7.1\Release\node-v46-win32-x64 )  else (node  configure --fallback-to-build --module=E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport\v1.7.1\Release\node-v46-win32-x64\serialport.node --module_name=serialport --module_path=E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport\v1.7.1\Release\node-v46-win32-x64 )
    
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport\v1.7.1\Release\node-v46-win32-x64\serialport.node --module_name=serialport --module_path=E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport\v1.7.1\Release\node-v46-win32-x64 )  else (node  build --fallback-to-build --module=E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport\v1.7.1\Release\node-v46-win32-x64\serialport.node --module_name=serialport --module_path=E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport\v1.7.1\Release\node-v46-win32-x64 )
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      serialport.cpp
      serialport_win.cpp
      enumser.cpp
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(263): error C2995: 'v8::Local
    <T> _NanEnsureLocal(v8::Local<T>)': function template has already been defined (compiling source file ..\src\serialport
    .cpp) [E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(263): error C2995: 'v8::Local
    <T> _NanEnsureLocal(v8::Local<T>)': function template has already been defined (compiling source file ..\src\serialport
    _win.cpp)E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(256): note: see decl
    aration of '_NanEnsureLocal' (compiling source file ..\src\serialport.cpp) [E:\dev\projects\sphero\node_modules\sphero\
    node_modules\serialport\build\serialport.vcxproj]
    
      E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(256): note: see declaration
       of '_NanEnsureLocal' (compiling source file ..\src\serialport_win.cpp)
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(661): error C3083: 'smalloc':
     the symbol to the left of a '::' must be a type (compiling source file ..\src\serialport.cpp) [E:\dev\projects\sphero\
    node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(661): error C2039: 'FreeCallb
    ack': is not a member of 'node' (compiling source file ..\src\serialport.cpp)E:\dev\projects\sphero\node_modules\sphero
    \node_modules\serialport\node_modules\nan\nan.h(661): error C3083: 'smalloc': the symbol to the left of a '::' must be
    a type (compiling source file ..\src\serialport_win.cpp) [E:\dev\projects\sphero\node_modules\sphero\node_modules\seria
    lport\build\serialport.vcxproj]
    
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(661): error C2039: 'FreeCallb
    ack': is not a member of 'node' (compiling source file ..\src\serialport_win.cpp) [E:\dev\projects\sphero\node_modules\
    sphero\node_modules\serialport\build\serialport.vcxproj]
      C:\Users\student\.node-gyp\4.1.1\include\node\node_object_wrap.h(8): note: see declaration of 'node' (compiling sourc
      e file ..\src\serialport.cpp)
      C:\Users\student\.node-gyp\4.1.1\include\node\node_object_wrap.h(8): note: see declaration of 'node' (compiling sourc
      e file ..\src\serialport_win.cpp)
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(661): error C2061: syntax err
    or: identifier 'FreeCallback' (compiling source file ..\src\serialport.cpp) [E:\dev\projects\sphero\node_modules\sphero
    \node_modules\serialport\build\serialport.vcxproj]
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(661): error C2061: syntax err
    or: identifier 'FreeCallback' (compiling source file ..\src\serialport_win.cpp) [E:\dev\projects\sphero\node_modules\sp
    hero\node_modules\serialport\build\serialport.vcxproj]
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(665): error C2065: 'callback'
    : undeclared identifier (compiling source file ..\src\serialport.cpp) [E:\dev\projects\sphero\node_modules\sphero\node_
    modules\serialport\build\serialport.vcxproj]
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(665): error C2065: 'callback'
    : undeclared identifier (compiling source file ..\src\serialport_win.cpp) [E:\dev\projects\sphero\node_modules\sphero\n
    ode_modules\serialport\build\serialport.vcxproj]
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(665): error C2065: 'hint': un
    declared identifier (compiling source file ..\src\serialport.cpp) [E:\dev\projects\sphero\node_modules\sphero\node_modu
    les\serialport\build\serialport.vcxproj]
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(665): error C2065: 'hint': un
    declared identifier (compiling source file ..\src\serialport_win.cpp) [E:\dev\projects\sphero\node_modules\sphero\node_
    modules\serialport\build\serialport.vcxproj]
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(672): error C2665: 'node::Buf
    fer::New': none of the 4 overloads could convert all the argument types (compiling source file ..\src\serialport.cpp) [
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
      C:\Users\student\.node-gyp\4.1.1\include\node\node_buffer.h(43): note: could be 'v8::MaybeLocal<v8::Object> node::Buf
      fer::New(v8::Isolate *,char *,size_t)' (compiling source file ..\src\serialport.cpp)
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(672): error C2665: 'node::Buf
    fer::New': none of the 4 overloads could convert all the argument types (compiling source file ..\src\serialport_win.cp
    p) [E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
      C:\Users\student\.node-gyp\4.1.1\include\node\node_buffer.h(43): note: could be 'v8::MaybeLocal<v8::Object> node::Buf
      fer::New(v8::Isolate *,char *,size_t)' (compiling source file ..\src\serialport_win.cpp)
      C:\Users\student\.node-gyp\4.1.1\include\node\node_buffer.h(31): note: or       'v8::MaybeLocal<v8::Object> node::Buf
      fer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)' (compiling source file ..\src\serialport.cpp)
      C:\Users\student\.node-gyp\4.1.1\include\node\node_buffer.h(31): note: or       'v8::MaybeLocal<v8::Object> node::Buf
      fer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)' (compiling source file ..\src\serialport_win.cpp)E:\dev
      \projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(672): note: while trying to match
       the argument list '(v8::Isolate *, const char *, uint32_t)' (compiling source file ..\src\serialport.cpp)
    
      E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(672): note: while trying to
       match the argument list '(v8::Isolate *, const char *, uint32_t)' (compiling source file ..\src\serialport_win.cpp)
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(676): error C2440: 'return':
    cannot convert from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>' (compiling source file ..\src\serialport.cp
    p) [E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
      E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(676): note: No constructor
      could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\src\serialport
      .cpp)
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(676): error C2440: 'return':
    cannot convert from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>' (compiling source file ..\src\serialport_wi
    n.cpp) [E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
      E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(676): note: No constructor
      could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\src\serialport
      _win.cpp)
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(683): error C2039: 'Use': is
    not a member of 'node::Buffer' (compiling source file ..\src\serialport_win.cpp)E:\dev\projects\sphero\node_modules\sph
    ero\node_modules\serialport\node_modules\nan\nan.h(683): error C2039: 'Use': is not a member of 'node::Buffer' (compili
    ng source file ..\src\serialport.cpp) [E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialp
    ort.vcxproj]
    
      C:\Users\student\.node-gyp\4.1.1\include\node\node_buffer.h(8): note: see declaration of 'node::Buffer' (compiling so
      urce file ..\src\serialport_win.cpp)
      C:\Users\student\.node-gyp\4.1.1\include\node\node_buffer.h(8): note: see declaration of 'node::Buffer' (compiling so
      urce file ..\src\serialport.cpp)
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(683): error C3861: 'Use': ide
    ntifier not found (compiling source file ..\src\serialport.cpp) [E:\dev\projects\sphero\node_modules\sphero\node_module
    s\serialport\build\serialport.vcxproj]
    E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\nan\nan.h(683): error C3861: 'Use': ide
    ntifier not found (compiling source file ..\src\serialport_win.cpp) [E:\dev\projects\sphero\node_modules\sphero\node_mo
    dules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(152): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int' [E:\dev\projects\
    sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(152): warning C4302: 'type cast': truncation from 'HANDLE' to 'int' [E:\dev\projects\sphero\n
    ode_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(177): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\win\enumser.cpp(443): warning C4996: 'GetVersionExA': was declared deprecated [E:\dev\projects\sphero\node_modul
    es\sphero\node_modules\serialport\build\serialport.vcxproj]
      C:\Program Files (x86)\Windows Kits\8.1\Include\um\sysinfoapi.h(433): note: see declaration of 'GetVersionExA'
    ..\src\serialport_win.cpp(179): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(183): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(185): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(189): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(191): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(196): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(208): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(308): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int' [E:\dev\projects\
    sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(308): warning C4302: 'type cast': truncation from 'HANDLE' to 'int' [E:\dev\projects\sphero\n
    ode_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(318): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int' [E:\dev\projects\
    sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(318): warning C4302: 'type cast': truncation from 'HANDLE' to 'int' [E:\dev\projects\sphero\n
    ode_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(328): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(353): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(366): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(401): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(403): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(502): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    ..\src\serialport_win.cpp(511): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size [E:\dev\p
    rojects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    e:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\src\win\stdstring.h(2123): warning C4311: 'reinterpr
    et_cast': pointer truncation from 'const void *' to 'unsigned long' (compiling source file ..\src\win\enumser.cpp) [E:\
    dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
      e:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\src\win\stdstring.h(2117): note: while compiling c
      lass template member function 'bool CStdStr<wchar_t>::TryLoad(const void *)' (compiling source file ..\src\win\enumse
      r.cpp)
      e:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\src\win\stdstring.h(2171): note: see reference to
      function template instantiation 'bool CStdStr<wchar_t>::TryLoad(const void *)' being compiled (compiling source file
      ..\src\win\enumser.cpp)
      e:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\src\win\stdstring.h(3982): note: see reference to
      class template instantiation 'CStdStr<wchar_t>' being compiled (compiling source file ..\src\win\enumser.cpp)
    e:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\src\win\stdstring.h(2123): warning C4302: 'reinterpr
    et_cast': truncation from 'const void *' to 'unsigned long' (compiling source file ..\src\win\enumser.cpp) [E:\dev\proj
    ects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    e:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\src\win\stdstring.h(2126): warning C4311: 'reinterpr
    et_cast': pointer truncation from 'const void *' to 'unsigned long' (compiling source file ..\src\win\enumser.cpp) [E:\
    dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    e:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\src\win\stdstring.h(2126): warning C4302: 'reinterpr
    et_cast': truncation from 'const void *' to 'unsigned long' (compiling source file ..\src\win\enumser.cpp) [E:\dev\proj
    ects\sphero\node_modules\sphero\node_modules\serialport\build\serialport.vcxproj]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Windows_NT 10.0.10240
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=E:\\dev\\projects\\sphero\\node_modules\\sphero\\node_modules\\serialport\\build\\serialport\\v1.7.1\\Release\\node-v46-win32-x64\\serialport.node" "--module_name=serialport" "--module_path=E:\\dev\\projects\\sphero\\node_modules\\sphero\\node_modules\\serialport\\build\\serialport\\v1.7.1\\Release\\node-v46-win32-x64"
    gyp ERR! cwd E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport
    gyp ERR! node -v v4.1.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport\v1.7.1\Release\node-v46-win32-x64\serialport.node --module_name=serialport --module_path=E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport\v1.7.1\Release\node-v46-win32-x64' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    node-pre-gyp ERR! System Windows_NT 10.0.10240
    node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\dev\\projects\\sphero\\node_modules\\sphero\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport
    node-pre-gyp ERR! node -v v4.1.1
    node-pre-gyp ERR! node-pre-gyp -v v0.6.7
    node-pre-gyp ERR! not ok
    Failed to execute 'node-gyp.cmd build --fallback-to-build --module=E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport\v1.7.1\Release\node-v46-win32-x64\serialport.node --module_name=serialport --module_path=E:\dev\projects\sphero\node_modules\sphero\node_modules\serialport\build\serialport\v1.7.1\Release\node-v46-win32-x64' (1)
    npm ERR! Windows_NT 10.0.10240
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sphero"
    npm ERR! node v4.1.1
    npm ERR! npm  v2.14.4
    npm ERR! code ELIFECYCLE
    
    npm ERR! serialport@1.7.1 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the serialport@1.7.1 install script 'node-pre-gyp install --fallback-to-build'.
    npm ERR! This is most likely a problem with the serialport package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-pre-gyp install --fallback-to-build
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls serialport
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     E:\dev\projects\sphero\npm-debug.log

## I there an easy way to fix this. Maybe with setting proper environment settings?

**Comment by polymouse** [comment]
Ah, its a problem building the serialport module, not the sphero.js module.
